# Generated by Django 4.2.15 on 2025-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(editable=False, unique=True)),
                ('refcount', models.IntegerField(default=0, editable=False)),
                ('lastupdate', models.DateField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['refcount', 'lastupdate'], name='collect_reg_refcoun_032d8d_idx')],
            },
        ),
    ]
